### ISSUE TITLE
Suggestion: Ad-hoc add to download list from webpage

### ISSUE THREAD

**Issue by JSRobles** [HoloArchivists/hoshinova#12]
Sometimes there are videos that I would like to download that don't match any of my filters, but stopping the app, editing the config, and restarting feels like a very clunky process to record a one off video.

It would be great if there were a way to ad-hoc add videos to the queue via a text box on the webpage.

I made a quick mock up to try and illustrate this.

![2022-08-10_18-21](https://user-images.githubusercontent.com/14141744/184040839-f28bd17a-6e4b-4082-a07b-6cdefb049e6a.png)

**Comment by hizkifw** [comment]
Hi, this is currently being worked on at https://github.com/HoloArchivists/hoshinova/pull/5
