### ISSUE TITLE
Add additional notifiers

### ISSUE THREAD

**Issue by giannoug** [HoloArchivists/hoshinova#26]
It would be nice if hoshinova supported additional notifiers apart from Discord.

**Comment by hizkifw** [comment]
Do you have any specific services you want/need?

**Comment by giannoug** [comment]
Not something specific. I need to get notified when a video is done. A simple webhook would be nice

**Comment by hizkifw** [comment]
If you want to write your own webhook handler, you can point the discord webhook URL to your own webserver. It sends an HTTP POST with a JSON body. You can check the schema from Discord's documentation.

https://discord.com/developers/docs/resources/webhook#execute-webhook

Other than that you'd have to be a bit more specific with what you need.

**Comment by hizkifw** [comment]
Closing this issue, feel free to file a new issue if you want a specific notifier implemented.
